#snakemake --cluster-config cluster_config.yaml --cluster "qsub -pe smp {cluster.num_cores}" -j 20

import os
# read config info into this namespace
configfile: "config.yaml"

include: "bamQC"

rule all:
    input:
        expand("{mapping_folder}/{sample}.sort.bam.bai", mapping_folder=config['mappings'], sample=config["samples"]),
        expand("{mapping_folder}/{sample}.sort.bam", mapping_folder=config['mappings'], sample=config["samples"]),
        os.path.join(config['mappings'], "BamQC.pdf")
        
rule hisat:
    input:
        forward = lambda wildcards: config["samples"][wildcards.sample]['forward'],
        reverse = lambda wildcards: config["samples"][wildcards.sample]['reverse'],
        splice_sites = config["splice_sites"]
    output:
        "{mapping_folder}/{sample}.bam"
    params:
        index = config["index"]
    log:
        "Logs/{mapping_folder}/{sample}_hisat_map.txt"
    shell:
        "(hisat2 --fr --threads {params.num_cores} -x {params.index} --known-splicesite-infile "
        "{input.splice_sites} -1 {input.forward} -2 {input.reverse} | samtools view "
        "-S -bo {output} -) 2> {log}"

rule sort_bam:
    input:
        rules.hisat.output
    output:
        "{mapping_folder}/{sample}.sort.bam"
    shell:
        "samtools sort -o {output} {input}"

rule samtools_index:
    input:
        rules.sort_bam.output
    output:
        "{mapping_folder}/{sample}.sort.bam.bai"
    shell:
        "samtools index {input}"

